# Generated by Django 3.2.9 on 2021-12-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACLResource',
            fields=[
                ('IdResource', models.AutoField(primary_key=True, serialize=False)),
                ('ResourceName', models.CharField(max_length=200)),
                ('ResourceStatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ACLRole',
            fields=[
                ('IdRole', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=200)),
                ('RoleStatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('IdSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('SolicitudDescription', models.CharField(max_length=5000)),
                ('SolicitudStatus', models.IntegerField()),
                ('SolicitudClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('SolicitudProfessional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.professional')),
            ],
        ),
        migrations.CreateModel(
            name='ACLUser',
            fields=[
                ('IdUser', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=40)),
                ('UserStatus', models.IntegerField()),
                ('UserRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aclrole')),
            ],
        ),
        migrations.CreateModel(
            name='ACLAccess',
            fields=[
                ('IdAccess', models.AutoField(primary_key=True, serialize=False)),
                ('AccessName', models.CharField(max_length=60)),
                ('AccessStatus', models.IntegerField()),
                ('AccessResource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aclresource')),
                ('AccessRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aclrole')),
            ],
        ),
    ]
