# Generated by Django 3.2.9 on 2021-12-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aclaccess_aclresource_aclrole_acluser_solicitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
