# Generated by Django 3.2.9 on 2021-12-12 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SolicitudDescription', models.CharField(max_length=5000)),
                ('SolicitudImg', models.ImageField(upload_to='pics')),
                ('SolicitudDate', models.DateField()),
                ('SolicitudAddress', models.CharField(max_length=100)),
                ('SolicitudPrice', models.FloatField()),
                ('SolicitudClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('SolicitudProfession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profession')),
            ],
        ),
    ]
